# runpod:
#   completion_llm_id: "vllm-ii509mysu8npnj"
#   timeout: 180
runpod:
  completion_llm:
    id: "vllm-ii509mysu8npnj"
    timeout: 200
  instruct_llm:
    id: "vllm-tgzegx5x5g1mr6"
    timeout: 200
