runpod:
  instruct_llm:
    id: "gt96iviaoxovi0"
    timeout: 2000
  indus_embedder:
    id: "bqwuhwmnb3bdx0"
    timeout: 1000
  reranker:
    id: "4947q1tk0d2lle"
    timeout: 1000

mistral:
  model: "mistral-large-latest"
  timeout: 3000


mcp:
  servers:
    eve-mcp-demo:
      url: "https://eve-mcp-demo.literatum.com/mcp"
      transport: "streamable_http"
      headers:
        Authorization: "eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJtY3AiXSwiZXhwIjoxNzU1NjEzMzg5LCJqdGkiOiIzYzg4YzIxZS1iZjk5LTRlNTYtOWIzMS1kZmM2ZmJhMjgyMGIiLCJjbGllbnRfaWQiOiJjQU9jdmw0Q3c5In0.SJc_39PQBBfWUng1WipOQcJSO7v5FWR4p1Mr3oy9kfQ"
      enabled: true
