runpod:
  instruct_llm:
    id: "x3kj159bf1ifn9"
    timeout: 40 # seconds in ChatOpenAI
  indus_embedder:
    id: "bqwuhwmnb3bdx0"
    timeout: 20
  reranker:
    id: "4947q1tk0d2lle"
    timeout: 20

mistral:
  model: "mistral-small-latest"
  timeout: 20 # seconds

mcp:
  servers:
    eve-mcp-demo:
      url: "https://eve-mcp-demo.literatum.com/mcp"
      transport: "streamable_http"
      enabled: true