runpod:
  instruct_llm:
    id: "gt96iviaoxovi0"
    timeout: 2000
  indus_embedder:
    id: "bqwuhwmnb3bdx0"
    timeout: 1000


mcp:
  server_url: "https://eve-mcp-demo.literatum.com/mcp"
  headers:
    Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJtY3AiXSwiZXhwIjoxNzU0NjYxMzEwLCJqdGkiOiIxNTlhMjQxYS02MWYxLTQ0MjgtODMxZS00YTNiY2Q1M2UzNDQiLCJjbGllbnRfaWQiOiJjQU9jdmw0Q3c5In0.BwjPEICb37xNgfV-i1_QcagCfcZkiRcOTeZPs0FYd1Y"
