runpod:
  instruct_llm:
    id: "gt96iviaoxovi0"
    timeout: 2000
  indus_embedder:
    id: "bqwuhwmnb3bdx0"
    timeout: 1000


mcp:
  server_url: "https://eve-mcp-demo.literatum.com/mcp"
  headers:
    Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJtY3AiXSwiZXhwIjoxNzU0NzUwMTE1LCJqdGkiOiI4MWQxN2I3Yy0xMmUxLTQ2ODEtYWVjNy1mMzI3MTI3YjIzYjIiLCJjbGllbnRfaWQiOiJjQU9jdmw0Q3c5In0.VhoH-xW1I_mp_VcpyC0Y1ZOtQm_wvTSmayiQRPq30Gc"
