runpod:
  instruct_llm:
    id: "gt96iviaoxovi0"
    timeout: 2000
  indus_embedder:
    id: "bqwuhwmnb3bdx0"
    timeout: 1000

mistral:
  model: "mistral-large-latest"
  timeout: 3000


mcp:
  servers:
    eve-mcp-demo:
      url: "https://eve-mcp-demo.literatum.com/mcp"
      transport: "streamable_http"
      headers:
        Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJtY3AiXSwiZXhwIjoxNzU0OTE0NjE1LCJqdGkiOiIzY2IyN2M4Yi00ODQ1LTQ0MTYtYjg2Ni1jOTRiNWJkN2E2NTMiLCJjbGllbnRfaWQiOiJjQU9jdmw0Q3c5In0.gJuHpsI9csIODP1NhvCkbY2fIJ7zLaWXtDtj9myVPEU"
      enabled: true
